name: curi_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  el_tooltip: ^2.0.0
  equatable: ^2.0.5
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.5.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations: 
    sdk: flutter
  flutter_spinkit: ^5.2.0
  get: ^4.6.5
  get_it: ^7.6.0
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: any
  percent_indicator: ^4.2.2
  permission_handler: ^10.3.0
  shared_preferences: ^2.1.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  


flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
  assets:
    - assets/
    - assets/images/Image_circle.png
    - assets/images/Image_circle2.png
    - assets/images/image_asset1.png
    - assets/images/image_asset2.png
    - assets/images/image_asset3.png
    - assets/images/image_asset4.png
    - assets/images/image_asset6.png
    - assets/images/image_asset7.png
    - assets/images/image_waiting.png
    - assets/images/image_enrollment.png
    - assets/images/pana.png
    - assets/images/image_newie.png
    - assets/images/onboarding_enroll_image.png
